[package]
name = "calimero-sys"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
publish = true

[dependencies]
cfg-if.workspace = true

[lints]
workspace = true
